name = "BaytesDiff"
uuid = "12a76ff9-393d-487f-8b39-e615b97e2f77"
authors = ["Patrick Aschermayr <p.aschermayr@gmail.com>"]
version = "0.1.0"

[compat]
julia = "1.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
